const StringConst = {
  Id: 'Id',
  Age: 'Age',
  Edit: 'Edit',
  city: 'City',
  Name: 'Name',
  apply: 'Apply',
  Hindi: 'Hindi',
  Cancel: 'Cancel',
  Update: 'Update',
  Delete: 'Delete',
  English: 'English',
  Sign_up: 'Sign up',
  add_data: 'Add Data',
  Gujarati: 'Gujarati',
  enter_age: 'Enter Age',
  Enter_Name: 'Enter Name',
  next_screen: 'Next Screen',
  no_Data_found: 'No Data Found',
  Enter_Password: 'Enter Password',
  Select_Language: 'Select Language',
  Create_New_Account: 'Create New Account',
  Enter_Email_Id_Name: 'Enter Email Id Name',
};

export default StringConst;
